DROP TABLE IF EXISTS Logging;

CREATE TABLE IF NOT EXISTS Logging (
    id INT AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(256) NOT NULL,
    IP VARCHAR(32) NOT NULL,
    endpoint VARCHAR(256) NOT NULL,
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Subscription;

CREATE TABLE IF NOT EXISTS Subscription (
    creator_id INT NOT NULL,
    subscriber_id INT NOT NULL,
    status ENUM('PENDING','ACCEPTED','REJECTED') NOT NULL DEFAULT 'PENDING',
    PRIMARY KEY (creator_id, subscriber_id)
);
